# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "cds-aws-lz-production-tf"
    dynamodb_table = "terraform-state-lock-dynamo"
    encrypt        = true
    key            = "main/terraform.tfstate"
    region         = "ca-central-1"
  }
}
