name: Terraform plan
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/**"
env:
  AWS_REGION: "ca-central-1"
  TERRAFORM_VERSION: 1.1.7
  TERRAGRUNT_VERSION: 0.36.3
  CONFTEST_VERSION: 0.30.0

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:

  terraform-plan-account:
    strategy:
      fail-fast: false
      matrix:
        include:
          - account_folder: org_account
            module: main
            account: 659087519042
            role: CDSLZTerraformReadOnlyRole

          - account_folder: log_archive
            module: main
            account: 274536870005
            role: CDSLZTerraformReadOnlyRole

          - account_folder: audit
            module: main
            account: 886481071419
            role: CDSLZTerraformReadOnlyRole

          - account_folder: aft
            module: main
            account: 137554749751
            role: CDSLZTerraformReadOnlyRole
            lz_webhook_key: LZ_CHANNEL_WEBHOOK

          - account_folder: org_account
            module: aft
            account: 659087519042
            role: CDSLZTerraformAdminPlanRole

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ matrix.account }}:role/${{ matrix.role }}
          role-session-name: ${{matrix.account}}-${{matrix.module}}-${{matrix.role}}-plan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan for ${{matrix.module }}/${{ matrix.module }}
        # I have no idea if this will work.
        env:
          TF_VAR_aft_slack_webhook: ${{ secrets[matrix.lz_webhook_key] }}
        uses: cds-snc/terraform-plan@v2
        with:
          comment-delete: true
          comment-title: Plan for ${{matrix.account_folder}}/${{ matrix.module }}
          directory: ./terragrunt/${{ matrix.account_folder }}/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
