name: Terraform plan
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terragrunt/**"
      - ".github/workflows/**"
env:
  AWS_REGION: "ca-central-1"
  TERRAFORM_VERSION: 1.1.7
  TERRAGRUNT_VERSION: 0.36.3
  CONFTEST_VERSION: 0.30.0

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan-org-account:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: main

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::659087519042:role/CDSLZTerraformReadOnlyRole
          role-session-name: CDSAWSLZGitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan for org_account/${{ matrix.module }}
        uses: cds-snc/terraform-plan@v2
        with:
          comment-delete: true
          comment-title: Plan for ${{ matrix.module }}
          directory: ./terragrunt/org_account/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true

  terraform-plan-aft-account:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: main

    runs-on: ubuntu-latest
    env:
      TF_VAR_aft_slack_webhook: ${{ secrets.LZ_CHANNEL_WEBHOOK }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::137554749751:role/CDSLZTerraformReadOnlyRole
          role-session-name: CDSAWSLZGitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan for aft/${{ matrix.module }}
        uses: cds-snc/terraform-plan@v2
        with:
          comment-delete: true
          comment-title: Plan for ${{ matrix.module }}
          directory: ./terragrunt/aft/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true


  terraform-plan-admin-aft-module:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup terraform tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::659087519042:role/CDSLZTerraformAdminPlanRole
          role-session-name: CDSAWSLZAdminPlanGitHubActions
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Plan for aft/${{ matrix.module }}
        uses: cds-snc/terraform-plan@v2
        with:
          comment-delete: true
          comment-title: Plan for AFT Root Module
          directory: ./terragrunt/org_account/aft
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
          plan-character-limit: 60000